### ISSUE TITLE
Chybaju udaje za rok 2015

### ISSUE THREAD

**Issue by katkad** [soit-sk/brno_sever_law_106#1]
z nejakeho dovodu tam nie su tieto data
http://www.sever.brno.cz/povinne-poskytovane-informace.html#naiqv_1

**Comment by michal-josef-spacek** [comment]
Jako u toho severniku. Je chyba v html kodu, kdy se tam prekryvaji tagy a tim padem to nejde stavajici technologii parsovat. Idealni jim napsat, at to opravi.

**Comment by katkad** [comment]
podla mna vykaslat sa na tagy, a brat si to rovno z tabuliek

**Comment by michal-josef-spacek** [comment]
Já tohle budu nějak řešit. Na tom parseru, co jsem dělal v sobotu zkouším přejít na jednodušší scrapování. Nestíhám :-)

**Comment by katkad** [comment]
vyriesene https://github.com/soit-sk/brno_sever_law_106/commit/dced023b1a78fb89e406c9d6cbc6fecd599431fa
na morphe to chodi

napr. severnik nema tables, tak tam to bude zlozitejsie

**Comment by michal-josef-spacek** [comment]
Dik :-)

**Comment by katkad** [comment]
;) zavieram
